# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.repository_owner }}

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Add GitHub Packages source
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/${{ env.GITHUB_USER }}/index.json" \
          --username ${{ env.GITHUB_USER }} \
          --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text \
          --name github
    - name: Restore dependencies
      run: dotnet restore --property:EnableWindowsTargeting=true
    - name: Build
      run: dotnet build --no-restore --property:EnableWindowsTargeting=true
    - name: Install and Trust Dotnet Dev Certificate
      run: |
        mkdir -p ${HOME}/.aspnet/https
        dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.crt --format PEM
        sudo cp ${HOME}/.aspnet/https/aspnetapp.crt /usr/local/share/ca-certificates/aspnetapp.crt
        sudo update-ca-certificates
    - name: Test
      run: dotnet test --no-build --verbosity normal --property:EnableWindowsTargeting=true
      env:
        Parameters__MigrationPerformingKey: "AnyRandomMigrationPerformingKey"
        JwtAuth__SigningKey: "Any sufficiently long enough key to sign the JWT Access Token with"
