name: .NET Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore --property:EnableWindowsTargeting=true
    - name: Build
      run: dotnet build --no-restore -c Release --property:EnableWindowsTargeting=true
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: . 

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: 
        - Fylum.Postgres.Shared.Tests
        - Fylum.Folders.Domain.Tests
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-output
        path: .
    - name: Restore Permissions
      run: find . -type f -path "*/bin/*" -exec chmod +x {} +
    - name: Run Unit Tests
      run: |
        dotnet test --project ${{ matrix.project }}/${{ matrix.project }}.csproj \
          --no-build -c Release --verbosity normal --property:EnableWindowsTargeting=true

  e2e-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: 
        - Fylum.EndToEnd
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-output
        path: .
    - name: Restore Aspire Components
      run: dotnet restore ${{ matrix.project }}/${{ matrix.project }}.csproj
    - name: Restore Permissions
      run: find . -type f -path "*/bin/*" -exec chmod +x {} +
    - name: Install and Trust Dotnet Dev Certificate
      run: |
        mkdir -p ${HOME}/.aspnet/https
        dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.crt --format PEM
        sudo cp ${HOME}/.aspnet/https/aspnetapp.crt /usr/local/share/ca-certificates/aspnetapp.crt
        sudo update-ca-certificates
    - name: Run End To End Test
      run: |
        dotnet test --project ${{ matrix.project }}/${{ matrix.project }}.csproj \
          --no-build -c Release --verbosity normal --property:EnableWindowsTargeting=true
      env:
        Parameters__MigrationPerformingKey: "AnyRandomMigrationPerformingKey"
        JwtAuth__SigningKey: "Any sufficiently long enough key to sign the JWT Access Token with"
