name: .NET Style Check

on:
  pull_request:
    branches: [ "*" ]

jobs:
  style-check:

    runs-on: ubuntu-latest
    env:
      GITHUB_USER: ${{ github.repository_owner }}

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Add GitHub Packages source
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/${{ env.GITHUB_USER }}/index.json" \
          --username ${{ env.GITHUB_USER }} \
          --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text \
          --name github
    - name: Restore dependencies
      run: dotnet restore --property:EnableWindowsTargeting=true
    - name: Verify Format with .editorconfig
      run: dotnet format --verify-no-changes --verbosity detailed --no-restore
